finally

diff --git a/.github/workflows/build_release.yaml b/.github/workflows/build_release.yaml
--- a/.github/workflows/build_release.yaml
+++ b/.github/workflows/build_release.yaml
@@ -12,10 +12,26 @@ jobs:
     steps: 
       - id: s01
         run: echo "github ${{ github.ref_name }}"
-      - run: echo "before " && ls -l
+      #- run: echo "before " && ls -l
       - id: s02
         uses: actions/setup-node@v4
         with:
           node-version: 24
       - id: s03
-        run: echo "before " && ls -l
+        uses: actions/checkout@v5
+        #run: echo "after " && ls -l
+      - id: s04
+        run: npm i -g @angular/cli && npm ci && echo "Angular CLI installed"
+    # fake error: echo "faking error" && exit 1
+      - id: s05
+        run: ng build  
+      - id: s06
+        run: echo "after build" && ls -l dist/countingbook/browser/
+      - id: s07
+        uses: nwtgck/actions-netlify@v3.0
+        with:
+            publish-dir: dist/countingbook/browser
+            production-deploy: true
+        env:
+            netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
+            netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
